In [ ]:
import numpy as np

a = np.array([[20, 40, 60, 80]])
print(np.append(a, [10, 700]))
print(np.insert(a, 1, 50))    #Array , index, value


[ 20  40  60  80  10 700]
[20 50 40 60 80]


In [4]:
print(np.delete(a, 1))  #Delete

[20 60 80]
