In [1]:
a = [10, 50, 40, 70]
b = [4, 3, 7, 5,]
print(a+b)

[10, 50, 40, 70, 4, 3, 7, 5]


In [14]:
#Concatenate

import numpy as np

arr1 = ([10, 50] , [40, 70])
arr2 = ([4, 3] , [7, 5])
print(np.concatenate([arr1, arr2]))

[[10 50]
 [40 70]
 [ 4  3]
 [ 7  5]]


In [15]:
print(np.concatenate([arr1, arr2],axis = 1 ))

[[10 50  4  3]
 [40 70  7  5]]


In [16]:
print(np.hstack([arr1, arr2]))   #Horizontal Concatenation

[[10 50  4  3]
 [40 70  7  5]]


In [17]:
print(np.vstack([arr1, arr2]))  #Vertical Concatenation

[[10 50]
 [40 70]
 [ 4  3]
 [ 7  5]]


In [20]:
a = np.array([20, 30, 40, 60, 80, 50])
print(np.array_split(a, 3))


[array([20, 30]), array([40, 60]), array([80, 50])]


In [21]:
a = np.array([20, 30, 40, 60, 80, 50])
b = np.array_split(a, 3)
print(b[1])


[40 60]
