In [ ]:
import numpy as np

arr1 = np.array([30, 40, 50, 10])
arr2 = np.array([20, 40, 50, 30])
print(arr1+arr2)
print(np.add(arr1, arr2))

In [1]:
import numpy as np

arr1 = np.array([30, 40, 50, 10])
arr2 = np.array([20, 40, 50, 30])
print(arr1-arr2)
print(np.subtract(arr1, arr2))

[ 10   0   0 -20]
[ 10   0   0 -20]


In [2]:
import numpy as np

arr1 = np.array([30, 40, 50, 10])
arr2 = np.array([20, 40, 50, 30])
print(arr1*arr2)
print(np.multiply(arr1, arr2))

[ 600 1600 2500  300]
[ 600 1600 2500  300]


In [3]:
import numpy as np

arr1 = np.array([30, 40, 50, 10])
arr2 = np.array([20, 40, 50, 30])
print(arr1/arr2)
print(np.divide(arr1, arr2))

[1.5        1.         1.         0.33333333]
[1.5        1.         1.         0.33333333]


In [5]:
import numpy as np

arr1 = np.array([2, 4, 1, 3])
arr2 = np.array([3])
print(np.power(arr1, arr2))

[ 8 64  1 27]
